#!/usr/bin/python3
import os
import time


__all__ = (
    "ADDRESS", "BUFF_SIZE", "UTF8", "PATH_TO_LOGS",
    "AUTO_LOGIN", "MAX_RECEIVED_MESSAGE",
    "S_CONNECT", "S_LOGIN", "S_OK", "S_ERROR",
    "S_START", "S_CHOOSE", "S_ROUND", "S_MOVE",
    "S_PLAYER_MOVE", "S_YOUR_MOVE", "S_YOUR_CHOICE",
    "S_PLAYER_CHOICE", "S_GAME_OVER_RESULTS",
    "H_EXIT_AFTER_CHOICE", "H_EXIT_DURING_GAME",
    "H_TIMEOUT", "H_SPAM", "SERVER", "CLIENT",
    "A_HACKER_MODE", "A_LOGIN", "ALLOWED_ARGS"
)

# CLIENT CONFIG
IP_SERVER = "127.0.0.1"
PORT = 5000
ADDRESS = (IP_SERVER, PORT)
BUFF_SIZE = 1024
UTF8 = "utf-8"
AUTO_LOGIN = True

# SCRIPT ARGS
A_HACKER_MODE = 'hacker_mode'
A_LOGIN = 'login'
ALLOWED_ARGS = [A_HACKER_MODE, A_LOGIN]

# HACKER CONFIG
MAX_RECEIVED_MESSAGE = 30
H_EXIT_AFTER_CHOICE = 'exit after choice'
H_EXIT_DURING_GAME = 'exit during game'
H_TIMEOUT = 'timeout'
H_SPAM = 'spamming'

# COMMANDS OF SERVER
S_CONNECT = "CONNECT"
S_LOGIN = "LOGIN"
S_START = "START"
S_YOUR_CHOICE = "YOUR CHOICE"
S_CHOOSE = "CHOOSE"
S_PLAYER_CHOICE = "PLAYER CHOICE"
S_YOUR_MOVE = "YOUR MOVE"
S_MOVE = "MOVE"
S_PLAYER_MOVE = "PLAYER MOVE"
S_GAME_OVER_RESULTS = "GAME OVER RESULTS"
S_ROUND = "ROUND"
S_OK = "OK"
S_ERROR = "ERROR"

# LOGGER CONFIG
SERVER = '[SERVER] -'
CLIENT = '[CLIENT] -'
FILENAME_LOGS = f'out-{str(int(time.time()))}.log'
DIRECTORY_LOGS = 'logs'
PATH_TO_LOGS = os.path.join(DIRECTORY_LOGS, FILENAME_LOGS)
