#!/usr/bin/python3
import os

__all__ = (
    "ADDRESS", "BUFF_SIZE", "UTF8",
    "TIMEOUT", "TIMEOUT_LOGIN", "CASTLE",
    "NUM_OF_ERRORS", "MAX_LENGTH_OF_MSG",
    "NUMBER_OF_PLAYERS", "ROUNDS",
    "S_CONNECT", "S_LOGIN", "S_OK", "S_ERROR",
    "S_START", "S_CHOOSE", "S_ROUND",
    "S_MOVE", "S_PLAYER_MOVE", "S_YOUR_MOVE",
    "S_YOUR_CHOICE", "S_PLAYER_CHOICE",
    "S_GAME_OVER_RESULTS","DIRECTORY_LOGS",
    "ALLOWED_CLIENT_COMMANDS",
    "SERVER", "CLIENT", "PATH_TO_LOGS"
)

# SERVER CONFIG
IP_SERVER = "127.0.0.1"
PORT = 5000
ADDRESS = (IP_SERVER, PORT)
BUFF_SIZE = 1024
UTF8 = "utf-8"
TIMEOUT = 2.0
TIMEOUT_LOGIN = 60
NUM_OF_ERRORS = 100
MAX_LENGTH_OF_MSG = 250

# GAME CONFIG
NUMBER_OF_PLAYERS = 4
ROUNDS = 12
PUZZLES_PER_ROUND = 4
CASTLE = 'CASTLE'

# COMMANDS OF SERVER
S_CONNECT = "CONNECT"
S_LOGIN = "LOGIN"
S_START = "START"
S_YOUR_CHOICE = "YOUR CHOICE"
S_CHOOSE = "CHOOSE"
S_PLAYER_CHOICE = "PLAYER CHOICE"
S_YOUR_MOVE = "YOUR MOVE"
S_MOVE = "MOVE"
S_PLAYER_MOVE = "PLAYER MOVE"
S_GAME_OVER_RESULTS = "GAME OVER RESULTS"
S_ROUND = "ROUND"
S_OK = "OK"
S_ERROR = "ERROR"

ALLOWED_CLIENT_COMMANDS = [S_LOGIN, S_CHOOSE, S_MOVE]

# LOGGER CONFIG
SERVER = '[SERVER] -'
CLIENT = '[CLIENT] -'
FILENAME_LOGS = 'out.log'
DIRECTORY_LOGS = 'logs'
PATH_TO_LOGS = os.path.join(DIRECTORY_LOGS, FILENAME_LOGS)
