#!/usr/bin/python3
import os
import time

# SERVER CONFIG
IP_SERVER = "127.0.0.1"
PORT = 5000
ADDRESS = (IP_SERVER, PORT)
BUFF_SIZE = 1024
UTF8 = "utf-8"
TIMEOUT = 2.0
TIMEOUT_LOGIN = 60
NUM_OF_ERRORS = 100
MAX_LENGTH_OF_MSG = 250

# GAME CONFIG
NUMBER_OF_PLAYERS = 4
ROUNDS = 12
PUZZLES_PER_ROUND = 4
CASTLE = 'CASTLE'

# CLIENT CONFIG
C_IP_SERVER = "127.0.0.1"
C_ADDRESS = (C_IP_SERVER, PORT)
AUTO_LOGIN = True

# SCRIPT ARGS
A_HACKER_MODE = 'hacker_mode'
A_LOGIN = 'login'
ALLOWED_ARGS = [A_HACKER_MODE, A_LOGIN]

# HACKER CONFIG
MAX_RECEIVED_MESSAGE = 30
H_EXIT_AFTER_CHOICE = 'exit after choice'
H_EXIT_DURING_GAME = 'exit during game'
H_TIMEOUT = 'timeout'
H_SPAM = 'spamming'

# COMMANDS OF SERVER
S_CONNECT = "CONNECT"
S_LOGIN = "LOGIN"
S_START = "START"
S_YOUR_CHOICE = "YOUR CHOICE"
S_CHOOSE = "CHOOSE"
S_PLAYER_CHOICE = "PLAYER CHOICE"
S_YOUR_MOVE = "YOUR MOVE"
S_MOVE = "MOVE"
S_PLAYER_MOVE = "PLAYER MOVE"
S_GAME_OVER_RESULTS = "GAME OVER RESULTS"
S_ROUND = "ROUND"
S_OK = "OK"
S_ERROR = "ERROR"

ALLOWED_CLIENT_COMMANDS = [S_LOGIN, S_CHOOSE, S_MOVE]

# LOGGER CONFIG
SERVER = '[SERVER] -'
CLIENT = '[CLIENT] -'
S_FILENAME_LOGS = 'out.log'
C_FILENAME_LOGS = f'out-{str(int(time.time()))}.log'
BASE_DIR = os.path.dirname(os.path.realpath(__file__))
DIR_LOGS = 'logs'
SERVER_DIR_LOGS = os.path.join(BASE_DIR, '..', DIR_LOGS, 'server')
CLIENT_DIR_LOGS = os.path.join(BASE_DIR, '..', DIR_LOGS, 'client')
SERVER_PATH_TO_LOGS = os.path.join(SERVER_DIR_LOGS, S_FILENAME_LOGS)
CLIENT_PATH_TO_LOGS = os.path.join(CLIENT_DIR_LOGS, C_FILENAME_LOGS)
LOGGER_NAME = 'logger'
